spring:
  application:
    name: arin-rpg

  datasource:
    url: jdbc:h2:file:./data/arin-rpg
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
jwt:
  secret=${JWT_SECRET:480f2046f4f7683ea455266c427f51b1}: